# Generated by Django 2.0.2 on 2018-02-28 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0002_auto_20180228_0912'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('id',), 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
