# Generated by Django 2.0.2 on 2018-02-28 07:25

import customuser.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0003_auto_20180228_1253'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', customuser.managers.UserManager()),
            ],
        ),
    ]
